# Generated by Django 4.2.30 on 2026-05-31 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
