# Generated by Django 4.2.30 on 2026-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sensor_devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('salinity', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_min', models.FloatField(default=4.0)),
                ('do_max', models.FloatField(default=9.0)),
                ('do_critical_min', models.FloatField(default=1.4)),
                ('do_critical_max', models.FloatField(default=12.0)),
                ('ph_min', models.FloatField(default=6.0)),
                ('ph_max', models.FloatField(default=8.0)),
                ('ph_critical_min', models.FloatField(default=4.0)),
                ('ph_critical_max', models.FloatField(default=10.0)),
                ('temp_min', models.FloatField(default=28.0)),
                ('temp_max', models.FloatField(default=32.0)),
                ('temp_critical_min', models.FloatField(default=25.0)),
                ('temp_critical_max', models.FloatField(default=35.0)),
                ('salinity_min', models.FloatField(default=28.0)),
                ('salinity_max', models.FloatField(default=33.0)),
                ('salinity_critical_min', models.FloatField(default=20.0)),
                ('salinity_critical_max', models.FloatField(default=40.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'thresholds',
            },
        ),
    ]
