# Generated by Django 4.2.30 on 2026-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=32, unique=True)),
                ('operator_email', models.EmailField(max_length=254)),
                ('operator_name', models.CharField(max_length=200)),
                ('note', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shift_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
