# Generated by Django 4.2.30 on 2026-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=32, unique=True)),
                ('action', models.CharField(choices=[('clear_all_alerts', 'Clear All Alerts'), ('resolve_alert', 'Resolve Alert'), ('create_manual_alert', 'Create Manual Alert'), ('update_threshold', 'Update Threshold'), ('set_history_window', 'Set History Window'), ('set_announcement', 'Set Announcement'), ('clear_announcement', 'Clear Announcement'), ('add_announcement_to_history', 'Add Announcement to History'), ('approve_user', 'Approve User'), ('deactivate_user', 'Deactivate User')], max_length=50)),
                ('actor_email', models.EmailField(max_length=254)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
